# Generated by Django 5.2.3 on 2025-07-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='category',
            new_name='categorie',
        ),
    ]
