# Generated by Django 5.2.3 on 2025-07-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0002_rename_category_produit_categorie'),
    ]

    operations = [
    ]
